name: biyung
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.8.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Viet
      fonts:
        - asset: fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
          style: normal
    - family: Biryani
      fonts:
        - asset: fonts/Biryani/Biryani-Regular.ttf
          style: normal
    - family: JosefinSans
      fonts:
        - asset: fonts/Josefin/JosefinSans-Regular.ttf
          style: normal
